Repository similarweb/statusbay, pull requests merged in 2020-03, with the labels that each got.

#199 Feature/add code coverage coveralls
  .github/workflows/go.yml
  README.md
Labels: enhancement, lgtm

#205 FIX: [ui] fix sort by namespace
  ui/client/src/components/Table/Table.js
Labels: bug, component-frontend, lgtm

#197 Set default sorting values if not specified
  ui/client/src/components/Table/Table.js
Labels: bug, component-frontend, lgtm

#198 fix unique key prop
  ui/client/src/components/Charts/Line/LineChartConfig.js
  ui/client/src/components/DeploymentStatusBox/index.js
  ui/client/src/components/EventsView/EventsView.js
  ui/client/src/components/EventsView/EventsViewLogs.js
  ui/client/src/components/Layout/Topbar/index.js
  ui/client/src/components/Table/Filters/DatePickerFilter.js
  ui/client/src/components/Table/TableStateless.js
  ui/client/src/containers/ApplicationDeployments.js
Labels: bug, component-frontend, lgtm

#203 FIX: [ui] fix filters reset whe trying to sort by a column
  ui/client/src/components/Table/Table.js
Labels: bug, component-frontend, lgtm

#201 FIX: [ui] fix react proptypes warnings
  ui/client/src/DataComponents/Kinds.js
  ui/client/src/DataComponents/ReplicaSetEvents.js
  ui/client/src/components/EventsView/EventViewSelector.js
  ui/client/src/components/EventsView/EventsView.js
  ui/client/src/components/EventsView/EventsViewLogs.js
  ui/client/src/components/ReplicasStats/ReplicasStatsBoxes.js
  ui/client/src/components/Table/TableStateless.js
  ui/client/src/components/Timeline/TimelineItem.js
Labels: bug, component-frontend, lgtm

#209 removed coverall due to wrong handling
  .github/workflows/go.yml
Labels: lgtm, ready-for-review

#174 DEV: [ui] stop calling metrics if we got enough points
  ui/client/src/DataComponents/Kinds.js
  ui/client/src/Hooks/MetricsHooks.js
  ui/server/api/controllers/deployment-metrics.js
  ui/server/socket/alerts.js
  ui/server/socket/metrics.js
  ui/server/test.js
Labels: component-frontend, enhancement, lgtm, ready-for-review

#208 Add the option to filter deployments by exact deployment name
  api/kubernetes/filter.go
  api/kubernetes/storage.go
  ui/client/src/Hooks/ApplicationsHooks.js
  ui/client/src/containers/ApplicationDeployments.js
  ui/server/api/controllers/applications.js
Labels: bug, component-api, component-frontend, lgtm, ready-for-review
